### PR TITLE
fix: remove buggy sudo-prompt until fallback works

### LINKED ISSUE #35: PWADevServer interactive password prompts should have CLI fallback
The [sudo-prompt](https://github.com/jorangreef/sudo-prompt#behavior) utility in PWADevServer creates OS-native privilege escalation prompts, graphical where possible. It should have a fallback condition if the current OS or execution environment is incompatible, where it uses a plain sudo prompt.

Steps to reproduce:

Initial setup: A Linux distribution without `pkexec` or `kdesudo` available.
OR, running `npm start` in a non-tty shell.

1. Set up `pwa-buildpack` in a theme repository.
2. Run an initial `npm start`.

Expected behavior: Some kind of sudo prompt.
Actual behavior: Hangs forever.

### PR DESCRIPTION
**Pull request by zetlen**
## This PR is a:
[ ] New feature
[ ] Enhancement/Optimization
[ ] Refactor
[x] Bugfix
[ ] Test for existing code
[ ] Documentation

## Summary

Removed the graphical `sudo-prompt` package and replaced it with a simple child_process call to sudo. Added custom prompt for command-line sudo for additional clarity for users.
When this pull request is merged, it will fix #35.
 

## Additional information

We want to go back to `sudo-prompt` eventually; I [began a branch to add sophisticated fallback behavior.](https://github.com/magento-research/pwa-buildpack/compare/zetlen/sudo-prompt-fallback) But this is good for MVP!

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento-research/pwa-buildpack?pullRequest=39) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento-research/pwa-buildpack?pullRequest=39) before we can accept your contribution.<br/>

File: src/util/run-as-root.js [hunk 1]
```diff
@@ -72,23 +68,41 @@ const sudoPromptToRunShell = async cmd =>
...
+ * @param {Function} fn JavaScript code to run. Must be a function. It can take
+ *     arguments, which must be passed in order in an array to the following
+ *     `args` parameter.
  * @param {Array} args An array of values to be passed as arguments. Must be
  *     serializable to JSON.
  * @returns {Promise<string>} A promise for the console output of the
  *     evaluated code. Rejects if the user did not authorize, or if the code
  *     threw an exception.
  */
 module.exports = async (fn, ...args) => {
```
Comment (jimbo) [inline src/util/run-as-root.js]: I see what's going on here with `prompt`, `fn`, and `func`, but it's a bit difficult to read. Maybe that's unavoidable.

It might be clearer to call argument 0 `prompt` instead of `fn`, default it to `'Temporary...'`, and go from there—you might be able to get rid of either `fn` or `func` that way.

Comment (zetlen) [reply src/util/run-as-root.js]: OK! I'm happy to make the change. I almost think that a description should simply be required, which would be more readable and maybe safer, since this is not a beginner-facing tool.

Comment (jimbo) [reply src/util/run-as-root.js]: Great, thanks for making that change. 👍

**Comment by zetlen** [comment]
Thanks, @jimbo . Merging!
